#!/usr/bin/env bash
# Configures Nginx to include a custom X-Served-By header with the server hostname

# Install nginx
sudo apt update -y
sudo apt install nginx -y

# Create custom header config
echo "add_header X-Served-By \$hostname;" | sudo tee /etc/nginx/conf.d/custom_header.conf

# Restart nginx
sudo service nginx restart
