#!/usr/bin/env bash
# This script installs and configures nginx web server

apt-get update -y
apt-get install nginx -y

# Ensure nginx is running
service nginx start

# Force correct content
echo "Holberton School" > /var/www/html/index.html

# Restart nginx (without systemctl)
service nginx restart
